image: maven:3.8.5-openjdk-17

stages:
  - build
  - test

build:
  stage: build
  script:
    - echo "Building the project"
    - mvn clean package
test:
  stage: test
  script:
    - echo "Running unit tests"
    - mvn test

